<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hE1QlHf' shared service.

return $this->privates['.service_locator.hE1QlHf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'albumRepository' => ['privates', 'App\\Repository\\AlbumRepository', 'getAlbumRepositoryService.php', true],
    'session' => ['services', 'session', 'getSessionService.php', true],
], [
    'albumRepository' => 'App\\Repository\\AlbumRepository',
    'session' => '?',
]);
