<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dM_4m1f' shared service.

return $this->privates['.service_locator.dM_4m1f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'picture' => ['privates', 'App\\Repository\\PictureRepository', 'getPictureRepositoryService.php', true],
], [
    'picture' => 'App\\Repository\\PictureRepository',
]);
