<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VnDuhb.' shared service.

return $this->privates['.service_locator.VnDuhb.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'album' => ['privates', '.errored..service_locator.VnDuhb..App\\Entity\\Album', NULL, 'Cannot autowire service ".service_locator.VnDuhb.": it references class "App\\Entity\\Album" but no such service exists.'],
], [
    'album' => 'App\\Entity\\Album',
]);
