<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.sZlj.d1' shared service.

return $this->privates['.service_locator.sZlj.d1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'picture' => ['privates', '.errored..service_locator.sZlj.d1.App\\Entity\\Picture', NULL, 'Cannot autowire service ".service_locator.sZlj.d1": it references class "App\\Entity\\Picture" but no such service exists.'],
], [
    'picture' => 'App\\Entity\\Picture',
]);
