<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Vo3hm6w' shared service.

return $this->privates['.service_locator.Vo3hm6w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'tagRepository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService.php', true],
], [
    'fileUploader' => 'App\\Service\\FileUploader',
    'manager' => '?',
    'tagRepository' => 'App\\Repository\\TagRepository',
]);
