<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SfYXIdc' shared service.

return $this->privates['.service_locator.SfYXIdc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authenticator' => ['privates', 'App\\Security\\AppCustomAuthenticator', 'getAppCustomAuthenticatorService.php', true],
    'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
    'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService.php', true],
    'guardHandler' => ['privates', 'security.authentication.guard_handler', 'getSecurity_Authentication_GuardHandlerService.php', true],
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'tokenGen' => ['privates', 'App\\Service\\TokenHandle', 'getTokenHandleService.php', true],
], [
    'authenticator' => 'App\\Security\\AppCustomAuthenticator',
    'dispatcher' => '?',
    'fileUploader' => 'App\\Service\\FileUploader',
    'guardHandler' => '?',
    'passwordEncoder' => '?',
    'tokenGen' => 'App\\Service\\TokenHandle',
]);
