<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\AdminRepository' shared autowired service.

include_once $this->targetDirs[3].'/src/Repository/AdminRepository.php';

return $this->privates['App\\Repository\\AdminRepository'] = new \App\Repository\AdminRepository();
