<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNosrJcb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNosrJcb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNosrJcb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNosrJcb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNosrJcb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NosrJcb',
    'container.build_id' => 'c55222d1',
    'container.build_time' => 1567618552,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNosrJcb');
